### ISSUE TITLE
RuntimeError: you must first build vocabulary before training the model

### ISSUE THREAD

**Issue by POMCP** [devmount/GermanWordEmbeddings#10]
I am getting this error when trying to train the model.

**Comment by devmount** [comment]
Can you provide a little more information like the whole error message / stack trace? How do you call the scripts?
Thanks.

**Comment by POMCP** [comment]
Script call:
`python training.py corpus/ model/my.model -s 300 -w 5 -n 10 -m 50`
```
 File "GermanWordEmbeddings/training.py", line 63, in <module>
    cbow_mean=args.cbowmean
  File "/home/sanket/DeepL/WordEmbeddings/InhouseNLU/lib/python3.5/site-packages/gensim/models/word2vec.py", line 479, in __init__
    start_alpha=self.alpha, end_alpha=self.min_alpha)
  File "/home/sanket/DeepL/WordEmbeddings/InhouseNLU/lib/python3.5/site-packages/gensim/models/word2vec.py", line 802, in train
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model
sanket@QADeepL:~/DeepL/WordEmbeddings$
```

**Comment by POMCP** [comment]
I used the wikipedia dump for this. Do you mean 50 for the word frequency is still large? I will try again with smaller numbers.

**Comment by devmount** [comment]
The wikipedia dump should definitely be large enough, so that is strange. Let me know if adjusting the `min_count` changes anything.
