### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by haemi** [devmount/GermanWordEmbeddings#13]
when I try to run the preprocessing I get the following error on MacOS:

```
  File "preprocessing.py", line 92, in <module>
    stop_words = [replace_umlauts(token) for token in stopwords.words('german')]
  File "preprocessing.py", line 52, in replace_umlauts
    res = res.replace('ä', 'ae')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

when using

`python preprocessing.py dewiki.xml corpus/dewiki.corpus -psub`

**Comment by haemi** [comment]
nevermind, finally got it working: with python3 everything works fine 🙂

**Comment by devmount** [comment]
Thanks for pointing this out. Would it be helpful, e.g. to always provide `$ python3 ....` examples in the readme?

**Comment by haemi** [comment]
I don't know - maybe at least mention it somewhere... although: now it is mentioned here 🙂

**Comment by devmount** [comment]
Ok. It is already mentioned at the beginning of the readme:

![image](https://user-images.githubusercontent.com/5441654/48293026-4a190a00-e47d-11e8-8b96-5df95f33fa5d.png)
