### ISSUE TITLE
plain text to segments

### ISSUE THREAD

**Issue by Tortoise17** [devmount/GermanWordEmbeddings#16]
I have plain German text without any stop or punctuation. It it possible to get sentence segments with this library?

**Comment by devmount** [comment]
No, not exactly. This project shows how to describe words as vectors. It uses a corpus that is a combination of sources already containing one sentence per line (German news articles) on the one hand and using preprocessing to recognize sentences based on punctuation (German Wikipedia) on the other hand.

To use Gensims word2vec (which is the case in this project), you have to already know which words belong to which sentence...

**Comment by Tortoise17** [comment]
Thank you for kind help. 
sentences are in sequence. But without stops. Is there any other tool which can handle such issue??

**Comment by devmount** [comment]
Can you give a short example of your data structure / how your corpus looks like exactly?

**Comment by Tortoise17** [comment]
data looks like 
ich Will die Scheidung was soll der Scheiß tut mir leid Sportsfreunde sehen war nicht so gemeint wie ich weiß ich suche ja schon

and then I want like 

ich Will die Scheidung. was soll der Scheiß. tut mir leid Sportsfreunde. sehen war nicht so gemeint wie ich weiß. Ich suche ja schon.

**Comment by devmount** [comment]
Got it. I don't know a tool that's capable of such a sentence estimation...  even for a human it's sometimes impossible to find the correct segmentation as there are many right possibilities with different meaning...
