### ISSUE TITLE
Provide citation info

### ISSUE THREAD

**Issue by LinqLover** [devmount/GermanWordEmbeddings#19]
I am using your work for writing my bachelor thesis, and on GitHub pages, I read that you created this project in the context of your bachelor thesis. Is it possible to cite you?

Unless instructed differently, I will link to your GitHub repository, but it would be great if you could add a DOI badge to your repo.

**Comment by devmount** [comment]
I'm glad, that this project is useful for you and thanks for this request. A DOI badge is a good idea, but I don't know when I will have time to register and implement it.  In the meantime, you can use this BibTex entry to cite this project:

```bibtex
@thesis{mueller2015,
  author = {{Müller}, Andreas},
  title  = "{Analyse von Wort-Vektoren deutscher Textkorpora}",
  school = {Technische Universität Berlin},
  year   = 2015,
  month  = jun,
  type   = {Bachelor's Thesis},
  url    = {https://devmount.github.io/GermanWordEmbeddings}
}
```

Let me know, if you need any further information.

**Comment by LinqLover** [comment]
Thank you!

**Comment by n1kt0** [comment]
Hi Christoph, may I know the topic of your thesis?

Best regards,
Nikita

Am Mi., 18. Nov. 2020 um 07:00 Uhr schrieb Andreas <notifications@github.com

**Comment by LinqLover** [comment]
No problem, but it is not published: _Exploring Museum-Related Social Media Posts Using Aspect-Based Sentiment Analysis_

**Comment by n1kt0** [comment]
Thanks a lot, I was just curious as I did sentiment analysis on Amazon
review data and also used this repository for my research.

Am Mi., 18. Nov. 2020 um 12:30 Uhr schrieb Christoph Thiede <
notifications@github.com>:
