### ISSUE TITLE
model evaluation & two error messages

### ISSUE THREAD

**Issue by matinho13** [devmount/GermanWordEmbeddings#3]
Great script!!!
After loading german.model the evaluation yielded nice results:
nouns: SI/PL: 26.8% (134/500), 60.0% (300/500), 100.0% (500/500)
nouns: PL/SI: 21.2% (106/500), 53.8% (269/500), 100.0% (500/500)
adjectives: GR/KOM: 40.8% (194/475), 69.9% (332/475), 95.0% (475/500)
adjectives: KOM/GR: 36.1% (170/471), 64.1% (302/471), 94.2% (471/500)
adjectives: GR/SUP: 10.3% (27/262), 31.3% (82/262), 52.4% (262/500)
adjectives: SUP/GR: 7.6% (21/276), 21.4% (59/276), 55.2% (276/500)
adjectives: KOM/SUP: 23.4% (60/256), 55.1% (141/256), 51.2% (256/500)
adjectives: SUP/KOM: 31.6% (83/263), 54.4% (143/263), 52.6% (263/500)
verbs (pres): INF/1SP: 78.0% (320/410), 95.6% (392/410), 82.0% (410/500)
verbs (pres): 1SP/INF: 71.8% (296/412), 93.7% (386/412), 82.4% (412/500)
verbs (pres): INF/2PP: 56.7% (208/367), 74.4% (273/367), 73.4% (367/500)
verbs (pres): 2PP/INF: 65.5% (237/362), 76.2% (276/362), 72.4% (362/500)
verbs (pres): 1SP/2PP: 54.4% (185/340), 65.3% (222/340), 68.0% (340/500)
verbs (pres): 2PP/1SP: 62.3% (223/358), 76.5% (274/358), 71.6% (358/500)
verbs (past): INF/3SV: 49.2% (210/427), 91.1% (389/427), 85.4% (427/500)
verbs (past): 3SV/INF: 40.3% (173/429), 92.8% (398/429), 85.8% (429/500)
verbs (past): INF/3PV: 78.4% (352/449), 97.1% (436/449), 89.8% (449/500)
verbs (past): 3PV/INF: 84.6% (369/436), 97.0% (423/436), 87.2% (436/500)
verbs (past): 3SV/3PV: 78.1% (356/456), 93.4% (426/456), 91.2% (456/500)
verbs (past): 3PV/3SV: 85.3% (390/457), 95.6% (437/457), 91.4% (457/500)
total correct:  52.0% (4114/7906)
total top 10:   75.4% (5960/7906)
total coverage: 79.1% (7906/10000)

However, when I tried: model.similarity(‘wort’,’klang') and got: KeyError("word '%s' not in vocabulary" % word). doing: python vocabulary.py DEmodel DEmodel.vocab got me: 'ascii' codec can't encode character u'\u2020' in position 0: ordinal not in range(128).

**Comment by gcarq** [comment]
> model.similarity(‘wort’,’klang')

Try to capitalize the input (e.g. `model.similarity(‘Wort’,’Klang')`)

> python vocabulary.py DEmodel DEmodel.vocab got me: 'ascii' codec can't encode character u'\u2020' in position 0: ordinal not in range(128).

it seems you are using python2, use python3 instead.

**Comment by matinho13** [comment]
khewl, thx a bunch!
