### ISSUE TITLE
german.model done with skip-gram or CBOW?

### ISSUE THREAD

**Issue by matinho13** [devmount/GermanWordEmbeddings#4]
you say 'I found the following parameter configuration to be optimal to train german language models with word2vec:
a corpus as big as possible (and as diverse as possible without being informal)
filtering of punctuation and stopwords
forming bigramm tokens
using skip-gram as training algorithm with hierarchical softmax
window size between 5 and 10
dimensionality of feature vectors of 300 or more
using negative sampling with 10 samples
ignoring all words with total frequency lower than 50'

so, you used skip-gram and not CBOW for training. what were the differences?
can one also access the bigram frequencies from german.model?

**Comment by devmount** [comment]
> you used skip-gram and not CBOW for training. what were the differences?

Skip-Gram with Hierarchical Softmax simply achieved better evaluation results than CBOW. Both architectures had nearly the same accuracy on syntax questions, but the Skip-Gram model answered 7% of the semantic questions more correctly than the CBOW model.

If you want, I can publish the corresponding figure of the evaluation results of the architecture test.

**Comment by matinho13** [comment]
thx!

I need the uni/bi/trigram frequencies of the corpus: can I read them out from german.model?
art

**Comment by devmount** [comment]
You can create the vocabulary out of the model using

    python vocabulary.py german.model german.model.vocab

This gives you the list of all distinct words in the model, stored in *german.model.vocab*. You can now simply count the words containing an underscore to get the number of bigram tokens. The list also contains a number of occurences in the corpus for each word. Is this what you want?

**Comment by matinho13** [comment]
sorry, aber ich krieg wieder das leidige: 'ascii' codec can't encode character u'\u2020' in position 0: ordinal not in range(128)
art

**Comment by matinho13** [comment]
muss wohl auf python 3 umsteigen, aber dann laufen ne menge meiner alten scripts nicht mehr…
a

**Comment by gcarq** [comment]
@matinho13 Sofern du Linux verwendest können python2 und python3 parallel installiert und verwendet werden, einzig die Script aufrufe ändern sich, zb.:
```
python2 legacy_py2_script.py
python3 script.py
```
Funktioniert sicher auch unter Windows, habe ich aber noch nie ausprobiert.

**Comment by devmount** [comment]
@matinho13: Die Lösung von @gcarq hab ich erfolgreich auch unter Windows 10 getestet. Einfach das [LinuxSubSystem unter Windows aktivieren](https://msdn.microsoft.com/de-de/commandline/wsl/install_guide?f=255&MSPPError=-2147217396), falls noch nicht vorhanden Python3 installieren 

    sudo apt-get install python3

pip/pip3 installieren und dann per 

    pip install gensim

bzw. `pip3 install gensim` für Python3 gensim installieren. So kannst du die Scripte aus dem Projekt parallel für beide Python Versionen ausführen.

<img width="304" alt="python23" src="https://user-images.githubusercontent.com/5441654/29026880-49d31144-7b7e-11e7-94fc-da437c0e653a.png">
