### ISSUE TITLE
Choose model type based on file extension

### ISSUE THREAD

**Issue by prabhakar267** [devmount/GermanWordEmbeddings#6]
You can set the type of model based on file extension instead of forcing it to be always binary, making it a generic embeddings evaluation system.

(https://github.com/devmount/GermanWordEmbeddings/blob/master/evaluation.py#L329)
```python
trained_model = gensim.models.KeyedVectors.load_word2vec_format(args.model.strip(), binary=True)
```

If it's a text file, then you can set binary as `False` (it's default value) and if not a text file, you can continue with current flow.

**Comment by devmount** [comment]
Thanks for the suggestion. You mean something like the following?

```python
is_text = Path(args.model.strip()).suffix == '.txt'
trained_model = gensim.models.KeyedVectors.load_word2vec_format(args.model.strip(), binary=is_text)
```

**Comment by prabhakar267** [comment]
And since [fastText](https://github.com/facebookresearch/fastText/) outputs a `.vec` file which has structure as any other `.txt` file
```
<vocabulary_size> <dimension_size>
<string> <vector>
...
...
```

**Comment by devmount** [comment]
Ok, feel free to create a pull request - I will check and merge it than.

**Comment by devmount** [comment]
Thanks for your request, I merged it and also added `.model` and no suffix at all as binary files for compatibility with my pretrained model.
