### ISSUE TITLE
Tests should be lowercased

### ISSUE THREAD

**Issue by prabhakar267** [devmount/GermanWordEmbeddings#8]
### Problem
I was using the repository for testing my trained model, one issue which i faced (and can be improved) is that all the test queries are capitalised and for a lot of reasons it is possible for someone to have lowercased every single word during training
 
### Improvement
Have one input parameter asking for the user to lowercase every query or not

**Comment by prabhakar267** [comment]
@devmount I will be more than willing to open a PR since I will be fixing it for my use-case but it would some time before I do that

**Comment by devmount** [comment]
Thanks for this request. Do you mean to build the test cases in lowercase (the `create_*()` functions in *evaluation.py* or to transform the model output to lowercase while testing (the `test_*()` functions in *evaluation.py*)?

**Comment by POMCP** [comment]
I tried loading your model in gensim, however got the error: 
`return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '6'.
`
I plan to use your model and further train it on my closed domain application.

**Comment by devmount** [comment]
@POMCP: Can you open a [new issue](https://github.com/devmount/GermanWordEmbeddings/issues/new) for your problem? It doesn't belong here to the lowercased test. Thanks!

**Comment by devmount** [comment]
@prabhakar267 Any update on this issue?

**Comment by prabhakar267** [comment]
@devmount I never ended up implementing the lowercase thing programatically
I lowercased the complete test file for time being
