### ISSUE TITLE
Invalid Load Key Error

### ISSUE THREAD

**Issue by POMCP** [devmount/GermanWordEmbeddings#9]
I tried loading your model in gensim, however got the error:
return _pickle.load(f, encoding='latin1') _pickle.UnpicklingError: invalid load key, '6'.
I plan to use your model and further train it on my closed domain application.

**Comment by devmount** [comment]
The model was saved in gensims word2vec format, using its built in load/save functions, not pickle. You would load the model like this:

    model = gensim.models.KeyedVectors.load_word2vec_format('german.model', binary=True)

**Comment by POMCP** [comment]
I think the flag, `binary=True ` was missing in the call I made to load the model.
